name: Deploy to ec2
on:
    push:
        branches:
            - main

jobs:
    compose_up:
        name: docker-compose up
        runs-on: ubuntu-latest
        steps:
            - uses: appleboy/ssh-action@master
              with:
                  host: ec2-13-232-122-12.ap-south-1.compute.amazonaws.com
                  username: ubuntu
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  port: 22
                  script_stop: true
                  script: |
                      docker pull tejashegde/messaging_app_client:latest
                      docker-compose up -d 
                      exit
