name: Build and push docker image
on:
    pull_request:
        branches:
            - main

jobs:
    build_client:
        name: Build client
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v2
              name: Checkout repo
            - env:
                  DOCKER_USER: ${{ secrets.DOCKER_USER }}
                  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
              run: |
                  docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
              name: Docker login
            - run: |
                  docker build -f dockerfile . -t tejashegde/pd_main_website
                  docker push tejashegde/pd_main_website
              name: Docker build and push
