name: Build and deploy
on:
    pull_request:
        branches:
            - main

jobs:
    build_client:
        name: Build client
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v2
              name: Checkout repo
            - env:
                  DOCKER_USER: ${{ secrets.DOCKER_USER }}
                  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
              run: |
                  docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
              name: Docker login
            - env:
                  MONGO_URI: ${{ secrets.MONGO_URI }}
                  PD_USERNAME: ${{ secrets.PD_USERNAME }}
                  PASSWORD: ${{ secrets.PASSWORD }}
                  WEBSITE_ADDR: ${{ secrets.WEBSITE_ADDR }}
              run: |
                  touch .env.local 
                  echo "MONGO_URI=$MONGO_URI" >> .env.local
                  echo "PD_USERNAME=$PD_USERNAME" >> .env.local
                  echo "PASSWORD=$PASSWORD" >> .env.local
                  echo "WEBSITE_ADDR=$WEBSITE_ADDR" >> .env.local
                  docker build -f dockerfile . -t tejashegde/pd_main_website
                  docker push tejashegde/pd_main_website
              name: Docker build and push
    compose_up:
        name: docker-compose up
        runs-on: ubuntu-latest
        needs:
            - build_client
        steps:
            - uses: appleboy/ssh-action@master
              with:
                  host: ec2-13-232-122-12.ap-south-1.compute.amazonaws.com
                  username: ubuntu
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  port: 22
                  script_stop: true
                  script: |
                      cd pd-main-website/ 
                      docker pull tejashegde/pd_main_website:latest
                      docker-compose up -d 
                      exit
